# Generated by Django 4.2.5 on 2023-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiEmprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
