# Generated by Django 4.2.5 on 2023-10-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiEmprendimiento', '0002_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='hacen_envios',
            field=models.BooleanField(default=False),
        ),
    ]
